### PR TITLE
Add new functions for Android

### PR DESCRIPTION
**Pull request by fegauthier**
I just add these new three functions.

- exitPlayer
- showController
- isControllerIsFullyVisible

### CODE REVIEW

**Comment by Aymkdn** [comment]
Awesome! I hope it will be merged :)

**Comment by jepiqueau** [comment]
@fegauthier @Aymkdn i am away travelling for the next three weeks so i will see if i have time to merge the PR. Thanks for your contribution and sorry for the inconvenience

**Comment by jepiqueau** [comment]
@fegauthier Can you explain the reasons for implementing this new functions and an app example demonstrating the use of them. Before to merge it i need to have this to see how it can be added also to others platforms to keep them aligned. Thanks to spend time to enhance the plugin.

**Comment by fegauthier** [comment]
> @fegauthier Can you explain the reasons for implementing this new functions and an app example demonstrating the use of them. Before to merge it i need to have this to see how it can be added also to others platforms to keep them aligned. Thanks to spend time to enhance the plugin.

I had an issue while using ExoPlayer. I don't know why, but events were not triggered on the ExoPlayerActivity but on my WebView activity. The only event that was triggered on the ExoPlayer view was the OK button. I pressed on the OK button to get controls to appear. Once the controls appeared, other buttons events was triggered to the Exo Player view has expected. When controls disappear, all events except the OK button are triggered on my WebView instead of the ExoPlayerActivity.

I implemented these functions to allow my web view to listen the events and triggering some actions on the ExoPlayer.

Example: Pressing Back Button. I want to exit player on this event. I added listener on my web view to call exitPlayer() when pressing this button on my remote.

Same thing for other events like Play/Pause, ForwardSkip, BackwardSkip etc.

The issue is that events are triggered to my web view instead of the ExoPlayer view. Except when the controls are shown in the ExoPlayer View.

**Comment by jepiqueau** [comment]
@fegauthier Can you send a small app demonstrating this. I am waiting your answer to decide to merge before moving to Capacitor5 which a lot of developers are waiting for. Thanks to provide this quickly

**Review by jepiqueau — APPROVED** [review]

**Pull request merged**
