### PR TITLE
Headers support for iOS and Android

### PR DESCRIPTION
**Pull request by PhantomPainX**
### What changed?
Headers support was added for Android and iOS. With this PR, headers can be used in as a dictionary of strings in _capVideoPlayerOptions_

### Why headers should be needed?
Sometimes when you have to access to a remote video url, some authorizations, referer or other headers needs to be passed in the request, otherwhise the video server end would deny your petition.

### Example (IONIC/Capacitor)
```
nativePlayer(video: any) {

    CapacitorVideoPlayer.initPlayer({
      mode: 'fullscreen',
      url: video.file,
      playerId: 'player1',
      headers: {
        Referer: video.referer
      }
    }).then(() => {
      console.log('Player initialized');
      CapacitorVideoPlayer.play({playerId: 'player1'}).then(() => {
        console.log('Player playing');
      });
    });
  }
```

### CODE REVIEW

**Comment by jepiqueau** [comment]
@PhantomPainX dis you test in ios if there is no headers will it work as you did not test for headers is nil

**Comment by jepiqueau** [comment]
@PhantomPainX don't you need to do this
If stHeaders != nil {
  self.videoAsset = AVURLAsset(url: url, options: ["AVURLAssetHTTPHeaderFieldsKey": stHeaders])
} else {
self.videoAsset = AVURLAsset(url: url)
}
When you will have answer i will merge the PR
Thanks for your contribution you should add you in the contributors liste in the readme and also add the explanations given above in the readme

**Comment by PhantomPainX** [comment]
> @PhantomPainX don't you need to do this If stHeaders != nil { self.videoAsset = AVURLAsset(url: url, options: ["AVURLAssetHTTPHeaderFieldsKey": stHeaders]) } else { self.videoAsset = AVURLAsset(url: url) } When you will have answer i will merge the PR Thanks for your contribution you should add you in the contributors liste in the readme and also add the explanations given above in the readme

Yeah, I forgot to add that condition in case there are not headers hahaha. I tested in Android too and the condition of `headers != null` in _FullscreenExoPlayerFragment.java_ was not enough, so I changed to `headers != null && headers.length() > 0`. It's stable in Android and iOS now.

Tested (Android): OnePlus 8T (Real device), Pixel 5 (Simulator) API 33
Tested (iOS): iPad Mini 5th (Real device), iPhone 13 (Simulator)

**Comment by jepiqueau** [comment]
@PhantomPainX thanks for your contribution

**Pull request merged**
