### PR TITLE
feat: hide close button

### PR DESCRIPTION
**Pull request by yelhouti**

### CODE REVIEW

**Comment by jepiqueau** [comment]
@yelhouti What is the reason behind hiding the close button? It is automatically hidden with the control bar. This button was added on request of developers.

**Comment by yelhouti** [comment]
@jepiqueau it is ugly :) , this just a flag when set to true manually hides the button, else it will be there

**Comment by jepiqueau** [comment]
@yelhouti i understand your view point but i try to keep the two (iOS and Android) plugin aligned. I will look what i can do in iOS

**Comment by yelhouti** [comment]
I get your point, thanks in advance :)

**Comment by jepiqueau** [comment]
i close this PR

**Pull request closed without merging**
